[workspace]
members = [
"templates/axum-tera-bulma",
]
resolver = "2"

[workspace.package]
name = "axumkit"
version = "2.0.0"
authors = ["Daiki Nakashima"]
edition = "2024"

[workspace.dependencies]
axum = { default-features = false, version = "0.8.4" }
tokio = { default-features = false, version = "1.45.1" }
hyper = { default-features = false, version = "1.6.0" }
tower = { default-features = false, version = "0.5.2" }
axum-template = "3.0.0"
tera = "1.20.0"
axum-macros = "0.5.0"
reqwest = { default-features = false, version = "0.12.20" }
http-body-util = "0.1.3"
