[package]
name = "axum-tera-bulma"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "http2", "macros", "tokio"] }
tokio = { workspace = true, features = ['full']}
hyper = { workspace = true, features = ['full']}
tower = { workspace = true, features = ['full']}
axum-template.workspace = true
tera.workspace = true
axum-macros.workspace = true

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["full"] }
